### ISSUE TITLE
master的数据持久化

### ISSUE THREAD

**Issue by leoYY** [baidu/galaxy#50]
需求：1. 记录snapshot，以及更改log      
           2. 数据维度包含jobMeta， taskInstanceMeta，以及SlaveMeta,不包含实时可检测的状态信息
问题：task_raw中程序包应该转储到管理程序包的存储介质中，task_raw只包含地址
设计：1. 数据存储在分布式存储中（leveldb/zk）
           2. 设计snapshot数据结果与log结构，log结构包含3种更新（1. job更新，2. instance更新，3. slave信息更新），且log包含时间戳以及持续递增的logid；snapshot结构，最后一次的log id，时间戳，以及对应的（job/instance/slave）的内存状态
           3. snapshot的生成可通过从上一个snapshot到现在的log生成
           4. snapshot生成后可清理之前的log数据
内容：1. master内存数据结构转pb，方便序列化
           2. task instance状态持久化，（实际部署位置变更）
           3. job meta信息持久化
           4. slave的注册状态持久化

**Comment by bluebore** [comment]
只持久化job信息有什么问题？
在NewJob，UpdateJob，KillJob存下盘
在启动时读取，恢复job信息。
其他信息通过query agent获取
